### PR TITLE
fix: refactor and fix flake

### LINKED ISSUE #733: [BUG] Cannot build .#eww with Nix
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

Eww cannot be build with nix after changes made on #722.

### Reproducing the issue

```
nix build 'github:elkowar/eww/642983a066931225aef43d4fba77c6d99e8d580d#eww'
error: builder for '/nix/store/kj68pkc9jrkh0v8xw4rzcdg509bg8ps5-eww-642983a066931225aef43d4fba77c6d99e8d580d.drv' failed with exit code 101;
       last 10 log lines:
       >   Package gtk-layer-shell-0 was not found in the pkg-config search path.
       >   Perhaps you should add the directory containing `gtk-layer-shell-0.pc'
       >   to the PKG_CONFIG_PATH environment variable
       >   No package 'gtk-layer-shell-0' found
       >   Package gtk-layer-shell-0 was not found in the pkg-config search path.
       >   Perhaps you should add the directory containing `gtk-layer-shell-0.pc'
       >   to the PKG_CONFIG_PATH environment variable
       >   No package 'gtk-layer-shell-0' found
       >
       > warning: build failed, waiting for other jobs to finish...
       For full logs, run 'nix log /nix/store/kj68pkc9jrkh0v8xw4rzcdg509bg8ps5-eww-642983a066931225aef43d4fba77c6d99e8d580d.drv'.
```
### Expected behaviour

Running `github:elkowar/eww#eww` should build successfully

### Additional context

```
~/git/eww master
❯ git bisect start                                        
status: waiting for both good and bad commits

~/git/eww master bisect
❯ git bisect good c72b881c3f8f2d2ad8d7a6c337ab3f55ff73ef4b
status: waiting for bad commit, 1 good commit known

~/git/eww master bisect
❯ git bisect bad e76206817de1cb86ec431dcff7d4b04c8b7d36fc
Bisecting: 2 revisions left to test after this (roughly 1 step)
[642983a066931225aef43d4fba77c6d99e8d580d] Default to building with both x11 and wayland (#722)

~/git/eww remotes/origin/fix-dangling-daemon~3 bisect
❯ git bisect run nix build .\#eww                        
running  'nix' 'build' '.#eww'
error: builder for '/nix/store/kj68pkc9jrkh0v8xw4rzcdg509bg8ps5-eww-642983a066931225aef43d4fba77c6d99e8d580d.drv' failed with exit code 101;
       last 10 log lines:
       >   Package gtk-layer-shell-0 was not found in the pkg-config search path.
       >   Perhaps you should add the directory containing `gtk-layer-shell-0.pc'
       >   to the PKG_CONFIG_PATH environment variable
       >   No package 'gtk-layer-shell-0' found
       >   Package gtk-layer-shell-0 was not found in the pkg-config search path.
       >   Perhaps you should add the directory containing `gtk-layer-shell-0.pc'
       >   to the PKG_CONFIG_PATH environment variable
       >   No package 'gtk-layer-shell-0' found
       >
       > warning: build failed, waiting for other jobs to finish...
       For full logs, run 'nix log /nix/store/kj68pkc9jrkh0v8xw4rzcdg509bg8ps5-eww-642983a066931225aef43d4fba77c6d99e8d580d.drv'.
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[de232de41b428b2caf1f41e021e67c0b86e65908] feat: `truncate-left` for labels (#721)
running  'nix' 'build' '.#eww'
642983a066931225aef43d4fba77c6d99e8d580d is the first bad commit
commit 642983a066931225aef43d4fba77c6d99e8d580d
Author: ElKowar <5300871+elkowar@users.noreply.github.com>
Date:   Sun Mar 26 12:09:03 2023 +0200

    Default to building with both x11 and wayland (#722)
    
    * Default to building with both x11 and wayland
    
    * Update CI to include tests and building for wayland and x11

 .github/workflows/build.yml                        |  12 +-
 CHANGELOG.md                                       |   1 +
 Cargo.lock                                         | 348 ++++++++++-----------
 crates/eww/Cargo.toml                              |  37 ++-
 crates/eww/src/app.rs                              |  18 +-
 crates/eww/src/display_backend.rs                  | 197 ++++++------
 crates/eww/src/main.rs                             | 178 ++++++-----
 crates/eww/src/opts.rs                             |   9 +-
 crates/eww/src/server.rs                           |  12 +-
 crates/yuck/Cargo.toml                             |   5 -
 crates/yuck/src/config/backend_window_options.rs   | 193 ++++++------
 .../snapshots/yuck__parser__test__test-10.snap     |   8 +
 .../snapshots/yuck__parser__test__test-11.snap     |   8 +
 .../snapshots/yuck__parser__test__test-12.snap     |   8 +
 .../snapshots/yuck__parser__test__test-13.snap     |   8 +
 .../snapshots/yuck__parser__test__test-14.snap     |   8 +
 .../snapshots/yuck__parser__test__test-15.snap     |   8 +
 .../snapshots/yuck__parser__test__test-16.snap     |   8 +
 .../snapshots/yuck__parser__test__test-17.snap     |   8 +
 .../snapshots/yuck__parser__test__test-2.snap      |   8 +
 .../snapshots/yuck__parser__test__test-3.snap      |   8 +
 .../snapshots/yuck__parser__test__test-4.snap      |   8 +
 .../snapshots/yuck__parser__test__test-5.snap      |   8 +
 .../snapshots/yuck__parser__test__test-6.snap      |   8 +
 .../snapshots/yuck__parser__test__test-7.snap      |   8 +
 .../snapshots/yuck__parser__test__test-8.snap      |   8 +
 .../snapshots/yuck__parser__test__test-9.snap      |   8 +
 .../parser/snapshots/yuck__parser__test__test.snap |   8 +
 28 files changed, 658 insertions(+), 488 deletions(-)
 create mode 100644 crates/yuck/src/parser/snapshots/yuck__parser__test__test-10.snap
 create mode 100644 crates/yuck/src/parser/snapshots/yuck__parser__test__test-11.snap
 create mode 100644 crates/yuck/src/parser/snapshots/yuck__parser__test__test-12.snap
 create mode 100644 crates/yuck/src/parser/snapshots/yuck__parser__test__test-13.snap
 create mode 100644 crates/yuck/src/parser/snapshots/yuck__parser__test__test-14.snap
 create mode 100644 crates/yuck/src/parser/snapshots/yuck__parser__test__test-15.snap
 create mode 100644 crates/yuck/src/parser/snapshots/yuck__parser__test__test-16.snap
 create mode 100644 crates/yuck/src/parser/snapshots/yuck__parser__test__test-17.snap
 create mode 100644 crates/yuck/src/parser/snapshots/yuck__parser__test__test-2.snap
 create mode 100644 crates/yuck/src/parser/snapshots/yuck__parser__test__test-3.snap
 create mode 100644 crates/yuck/src/parser/snapshots/yuck__parser__test__test-4.snap
 create mode 100644 crates/yuck/src/parser/snapshots/yuck__parser__test__test-5.snap
 create mode 100644 crates/yuck/src/parser/snapshots/yuck__parser__test__test-6.snap
 create mode 100644 crates/yuck/src/parser/snapshots/yuck__parser__test__test-7.snap
 create mode 100644 crates/yuck/src/parser/snapshots/yuck__parser__test__test-8.snap
 create mode 100644 crates/yuck/src/parser/snapshots/yuck__parser__test__test-9.snap
 create mode 100644 crates/yuck/src/parser/snapshots/yuck__parser__test__test.snap
bisect found first bad commit
```

### LINKED ISSUE #775: Building EWW as flake: gtk-layer-shell-0.pc not found
Hello, I'm running NixOS and trying to include EWW as a package in my system by using flakes. Here are some relevant code snippets:
Inputs to my `flake.nix`:
```
  inputs = {
    nixpkgs.url = "nixpkgs/nixos-unstable";
    nixpkgs-unstable.url = "nixpkgs/nixos-unstable";

    eww-git.url = "github:elkowar/eww";
  };
```

This is how I add eww to my system packages:
```
  environment.systemPackages = with pkgs; [
    # other stuff...
    inputs.eww-git.packages.x86_64-linux.eww
  ]
```

When I go to build my system with `nixos-rebuild`, nix begins to build eww but stops at this error:
```
error: builder for '/nix/store/77zg2i9azcmgm6wg8c0ql89kkxm4k4xp-eww-e76206817de1cb86ec431dcff7d4b04c8b7d36fc.drv' failed with exit code 101;
       last 10 log lines:
       >   Package gtk-layer-shell-0 was not found in the pkg-config search path.
       >   Perhaps you should add the directory containing `gtk-layer-shell-0.pc'
       >   to the PKG_CONFIG_PATH environment variable
       >   No package 'gtk-layer-shell-0' found
       >   Package gtk-layer-shell-0 was not found in the pkg-config search path.
       >   Perhaps you should add the directory containing `gtk-layer-shell-0.pc'
       >   to the PKG_CONFIG_PATH environment variable
       >   No package 'gtk-layer-shell-0' found
       >
       > warning: build failed, waiting for other jobs to finish...
       For full logs, run 'nix log /nix/store/77zg2i9azcmgm6wg8c0ql89kkxm4k4xp-eww-e76206817de1cb86ec431dcff7d4b04c8b7d36fc.drv'.
```

Some interesting notes:
1. Installing the wayland package works fine (`inputs.eww-git.packages.x86_64-linux.eww-wayland`)
2. I was able to clone the repository and build it myself. I would run `nix-shell` in the repository's root directory, and then `cargo build --release --no-default-features --features x11` to build EWW. That works.

Looking for assistance regarding this issue. It seems to me like an issue with the `flake.nix` in eww's repository, but I'm not knowledgeable enough in Nix or EWW yet to understand.

Thanks for reading

### LINKED ISSUE #817: [BUG] nix flake requires having rust-overlay installed separately
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

When building from the nix flake, I get an error if I do not have the rust-overlay flake installed even thought it is declared as a dependency in eww's flake.

### Reproducing the issue

1. Using a flake-based NixOS setup, add eww's flake, add its overlay, either enable eww in home manager or install its package, and run `nixos-rebuild test`. This should fail with an error from nix saying `error: attribute 'rust-bin' missing`
2. Add rust-overlay as a flake input, add its overlay, and run `nixos-rebuild test` again. Eww should build and install successfully.

### Expected behaviour

I expected to not need to manually set up `rust-overlay` for eww to successfully build.

### Additional context

```
error:
       … while calling the 'head' builtin

         at /nix/store/vby8c3909sglr03fxkclkly29vs49ncy-source/lib/attrsets.nix:784:11:

          783|         || pred here (elemAt values 1) (head values) then
          784|           head values
             |           ^
          785|         else

       … while evaluating the attribute 'value'

         at /nix/store/vby8c3909sglr03fxkclkly29vs49ncy-source/lib/modules.nix:759:9:

          758|     in warnDeprecation opt //
          759|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          760|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: attribute 'rust-bin' missing

       at /nix/store/a0h8yw7sjr5i75x5s0s3jj1lkz15h1xb-source/flake.nix:21:31:

           20|       targetSystems = [ "aarch64-linux" "x86_64-linux" ];
           21|       mkRustToolchain = pkgs: pkgs.rust-bin.fromRustupToolchainFile ./rust-toolchain.toml;
             |                               ^
           22|     in
```

### LINKED ISSUE #1036: [BUG] Nix Flake wayland output is still broken
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

The `eww` and `eww-wayland` package outputs of the nix flake are currently broken on wayland.
This should have been fixed by #1032, but I overlooked something, I would like to apologize for my mistake there.
There are a few ways to resolve this, but I believe that I lack the experience to judge how this should be done.
1. Wait until NixOS/nixpkgs#289595 is merged and makes it into nixpkgs-unstable, then simply update the `flake.lock` file
2. This can be done right now: Revert [this line](https://github.com/elkowar/eww/blob/7bfd47eb8130f02f2a8f695c255df2f5302636b4/flake.nix#L47) to
`eww-wayland = final.eww.override { withWayland = true; };`, this will work temporarily until the aforementioned pr is merged and the lockfile is updated, then the `eww-wayland` output will no longer evaluate.
3. Change the options that cargo builds with. I'm sure that this is possible, but it can't simply be done by changing the overlay as far as I'm concerned and due to exams I currently don't have the time to look into this further. It would also be no longer needed once the pr is merged and the lockfile is updated.

### Reproducing the issue

Run `nix build` or `nix build .#eww-wayland`, nix will instruct cargo to build with the flags `--no-default-features --features=x11`, as specified [here](https://github.com/NixOS/nixpkgs/blob/b7aa428f8a74280ecc3d140f28f099a1e20b34eb/pkgs/applications/window-managers/eww/default.nix#L30-L33).

### Expected behaviour

Cargo should build with default features.

### Additional context

Once again, I am deeply sorry for overlooking this, I think it would be best to wait for the merge and then simply update the lockfile. My belief that this works is based on changing the `nixpkgs` url to `"github:coffee-is-power/nixpkgs/patch-1"`, which results in a correctly functioning binary.
Anything that resolves this issue should also result in #733, #775 and #817 being resolved.

On a different note, I believe that the current flake structure isn't that good due to the heavy reliance on `nixpkgs`, which is also why it's currently half broken. I admittedly don't know whether this is standard practice or not, I think it'd be a better idea to use the package in the overlay, not the other way around, but I can't rule out that I have made yet another mistake in understanding the inner works of all of this.

### Temporary fix

**Update: Use the pr as it should now be ready for a merge and is therefore in a usable state**
Use [this branch](https://github.com/w-lfchen/eww/tree/flake) from #1038 until the pr is merged:
```nix
{
  # url = "github:elkowar/eww";
  inputs.nixpkgs.follows = "nixpkgs";
  # use this until https://github.com/elkowar/eww/issues/1038 is merged
  url = "github:w-lfchen/eww/flake";
};
```
It shouldn't matter whether you override `nixpkgs` or not, please tell me if it does matter as this is not expected behavior.

### PR DESCRIPTION
**Pull request by w-lfchen**
## Description

- Refactor the flake structure so that the package outputs no longer depend on the overlay, as this is highly prone to breaking
- Fix the wayland support of the output by doing that 
- The flake should now be a lot more stable and less likely to break since its outputs no longer heavily rely on the ways [nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/window-managers/eww/default.nix) does things.
- This means that `inputs.nixpkgs.follows = "nixpkgs";` should no longer break anything as long as `nixpkgs` isn't extremely out of date
- Update `flake.lock`

Fixes #1036 
Should do the following:
- fix #733 
- fix #775 
- fix #817

## Additional Notes

- This should have been done in #1032, I didn't want to touch the flake structure back then, this was a mistake for which I would like to apologize alongside my insufficient testing.
- Once this pr is open, I promise to have tested it in all the ways I can think of.
- Some changes might be subjective, for example the versioning scheme, I am open to discussion on everything.

## Checklist

- [x] I added my changes to CHANGELOG.md, if appropriate.
- [x] I used `cargo fmt` to automatically format all code before committing.
- [x] I used `nix fmt` to automatically format all code before committing.

### CODE REVIEW

**Comment by Cloudef** [comment]
Can confirm that these changes work https://github.com/Cloudef/nixos-flake/commit/a5103ea5556aa3d13aa16c230faec46dbff73b7f

**Comment by w-lfchen** [comment]
This now also addresses these lines added in https://github.com/elkowar/eww/commit/1b819fb6469a3fb7fa9eb39d73eaefeb768be027: https://github.com/elkowar/eww/blob/1b819fb6469a3fb7fa9eb39d73eaefeb768be027/flake.nix#L45-L46

**Comment by MatthieuBarthel** [comment]
I've just tried this flake and it's working well.

It would be nice to provide an overlay, by adding this at the end of your flake.nix (sorry I failed to make a github suggestion):

```nix
      formatter =
        nixpkgs.lib.genAttrs targetSystems (system: (pkgsFor system).nixfmt);
    } // {
      overlay = final: prev: {
        eww = self.packages.${final.system}.eww;
      };
    };
}
```

People would then be able to use latest eww on their system:
```nix
{
  inputs = {
    eww.url = "github:elkowar/eww";
    nixpkgs.url = "nixpkgs/nixos-23.11";
  };

  outputs = { eww, nixpkgs, ... }:
  let
    system = "x86_64-linux";
    pkgs = import nixpkgs {
      inherit system;
      overlays = [ eww.overlay ];
    };
    ....
```

**Comment by w-lfchen** [comment]
> It would be nice to provide an overlay

@MatthieuBarthel This flake already provides an overlay, as specified here:
https://github.com/elkowar/eww/blob/833ffeba31854fc54eea81e8cac59f8768808234/flake.nix#L23-L25

I am using it without issues, if it doesn't work for you please tell me and I'll look into it.

`nix flake show` contains the following output:
```
├───overlays
│   └───default: Nixpkgs overlay
```

In order to make suggestions, you need to head to the "Files changed" view, [this article](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request) might be able to help you.

**Comment by MatthieuBarthel** [comment]
Oh thank you @w-lfchen, I have to improve my internal nix parsing 😅

I successfully used the provided overlays in my flake using this syntax `overlays = [ eww.overlays.default ];`

**Comment by w-lfchen** [comment]
@elkowar what is stopping this pr from being merged?
I'd love to improve things if you think that there's need for it

**Comment by elkowar** [comment]
Nothing is stopping it from  being merged 😉 Thanks for your contribution!

**Pull request merged**
