### PR TITLE
Added support to label text alignment.

### PR DESCRIPTION
**Pull request by AlecsFerra**
## Description
Since labels in gtk can't be aligned via css (I still don't know why)
and can be only aligned using code, this patch adds support for this
functionality by adding the properties :xalign and :yalign to the label
expression.
The exact behavior is described by the docs.

## Usage
```scm
(defwindow test
           :geometry (geometry :anchor "bottom left"
                               :x      "52px"
                               :y      "-12px"
                               :width  "370px"
                               :height "216px")
           (test))

(defwidget test []
           (box :alignment "h"
           (label :xalign 0 :text "x-0")
           (label :xalign 1 :text "x-1")
           (label :yalign 0 :text "y-0")
           (label :yalign 1 :text "y-1")
           (label :xalign 0.69 :yalign 0.420 :text "special")))
```

### Showcase
Right now:
image

With this patch:
image

## Checklist

Please make sure you can check all the boxes that apply to this PR.

- [X] All widgets I've added are correctly documented.
- [x] I added my changes to CHANGELOG.md, if appropriate.
- [X] The documentation in the `docs/content/main` directory has been adjusted to reflect my changes.
- [X] I used `cargo fmt` to automatically format all code before committing

### CODE REVIEW

**Comment by elkowar** [comment]
This is pretty cool! I'm not sure if I'm a fan of the names xalign and yalign tho, as those sound _very_ similar to the `halign` and `valign` properties that exist in other places and take other values,...
Do you have any other ideas on how we could name the properties?

**Comment by AlecsFerra** [comment]
Honestly I don't know maybe the full word `verticalAlign`?

**Comment by elkowar** [comment]
I don't think that's better... I'll do some more thinking, and if I don't come up with anything we can stick to xalign and yalign.

Also, just saw your example using 0.69 and 0.420, very nice!

**Comment by elkowar** [comment]
merging this, as I can't think of any better name

**Pull request merged**
