### PR TITLE
inotify scheduler for script vars

### PR DESCRIPTION
**Pull request by legendofmiracles**
## Description

Adds another scheduler for script-vars, which will execute the command whenever a file/directory changes.

## Usage

e.g. 
```xml
<script-var name="test" files="[/home/user/test,/sys/class/power_supply/]/>
```

## Additional Notes

See the docs I added.

### CODE REVIEW

**Comment by elkowar** [comment]
Do you have a concrete usecase example for this? In it's current state, this seems,.. rather confusing (both in terms of code, and for the user) - where would a simple script-var (if necessary, using sth like `entr`) not suffice?

**Comment by Animeshz** [comment]
Can't we just use a listening variable for this? We can easily spawn bg child processes (with `&`) monitored by linux itself. Making sleep/loop is easy either.

**Comment by undefinedDarkness** [comment]
Cant you just use entr or smth

**Comment by legendofmiracles** [comment]
Fine, I'm too lazy to resolve the merge conflicts anyways..

**Pull request closed without merging**
