### PR TITLE
Updated Shell.nix

### PR DESCRIPTION
**Pull request by Vertecedoc4545**
Bug corretion: error: infinite recursion encountered, at undefined position

Please follow this template, if applicable.

## Description

Wen trying to build on nixos the nix shell doesn't work, the problem is the shell.nix file that on nix 2.3 create an error of infinite recursion, this pull request repair the issue reformating the shell.nix file

## Usage

install nix package manager or nixos then clone the repo and for be able to build the project use the nix-shell command, there you will have the shell with the needed sources for the build

## Checklist

Please make sure you can check all the boxes that apply to this PR.

- [x] The documentation in the `docs/content/main` directory has been adjusted to reflect my changes.
- [x] I used `cargo fmt` to automatically format all code before committing

### CODE REVIEW

**Comment by HeavyRain266** [comment]
@Vertecedoc4545 without `npkgs.gtk-layer-shell` build fails for wayland even if packages is instaleld system-wide. I suggest you to add it.

**Comment by JavaCafe01** [comment]
@Vertecedoc4545 Use `nix develop`

**Comment by legendofmiracles** [comment]
No, this is still an issue. Not everyone uses the new nix cli, the newest nixos release doesn't even ship with it by default.

**Comment by legendofmiracles** [comment]
Although I'd be more in favor of merging: https://github.com/elkowar/eww/pull/327. It's more pure (doesn't rely on system state), and uses the idiomatic way of combining old cli with the newer flakes.

**Comment by elkowar** [comment]
@JavaCafe01 onions? (for reference, I have genuinely no idea about nix stuff, so I'm relying on the experts here lol)

**Comment by JavaCafe01** [comment]
@elkowar Lom is right. I would also be in favor of merging #327 over this one.

**Comment by elkowar** [comment]
Merged #327 over this, as recommended by f2k, javacafe and capli. Thanks for your efforts tho, I really appreciate it (eventhough I _did_ take wayyyyyyyyyyyyy to long to do any of this, lol)

**Pull request closed without merging**
