### PR TITLE
Added support for custom config dir path

### LINKED ISSUE #67: [FEATURE] A -c flag to specify config location.
## Description of the requested feature
Just a -c flag to specify config location, e.g `eww open main_window -c ~/Documents/eww.xml` 

## Proposed configuration syntax
```
 `eww open main_window -c ~/Documents/eww.xml` 
```
# Additional context
just like polybar does

### PR DESCRIPTION
**Pull request by druskus20**
## Description

This PR implements support for a user specified config directory path. It aims to fix #67.

## Usage

Simply run the program with the arguments `-c [config_dir_path]` or `--config [config_dir_path]`

## Checklist

Please make sure you can check all the boxes that apply to this PR.

- [x] All widgets I've added are correctly documented.
- [ ] The documentation in the `docs/content/main` directory has been adjusted to reflect my changes.
- [x] I used `cargo fmt` to automatically format all code before committing

## TODO: 
- Update documentation
- I think the way server.rs handles configuration paths could be cleaned up a bit.

### CODE REVIEW

**Comment by elkowar** [comment]
The code, as it currently is, wouldn't be able to properly deal with me _not_ specifying a config path, no? if no `-c` is specified, it should continue to default to `~/.config/eww/`

**Comment by druskus20** [comment]
It should fallback to default which in this case would be CONFIG_DIR. Take a look at server.rs lines 24 to 30.
Here

**Comment by alx365** [comment]
merge this before the edit subcommand (if you are still planning on merging it)

**Comment by elkowar** [comment]
Still to do: not use empty string, but set a fallback value properly directly or at least use `Option<T>`
(first option would be to set the actual config path in the structopt macro, not sure if that's possible).
@druskus20 u gonna finish this? :P

**Pull request closed without merging**
