### PR TITLE
[FEATURE] Add trigonometric functions

### PR DESCRIPTION
**Pull request by end-4**
## Description

- This PR introduces four trigonometric functions to the expression language: sine, cosine, tangent, cotangent 
- Why? For making radial menus with less hard-coding or external calculation

## Usage

- As noted in documentation:
   - `sin(number)`, `cos(number)`, `tan(number)`, `cot(number)`: Calculate the trigonometric value of a given number in **radians**
    - `sindeg(number)`, `cosdeg(number)`, `tandeg(number)`, `cotdeg(number)`: Calculate the trigonometric value of a given number in **degrees**
- The following code is for a box containing text that uses some of the above functions
```lisp
(defwidget test_widget []
  (box
    :width 300 :height 100
    "
    cos(0rad) = ${cos(0)} 
    sin(30deg) = ${sindeg(30)}
    tan(60deg) = ${tandeg(60)}
    cot(0.785398rad) = ${cot(0.785398)}
    "))

(defwindow test
  :monitor 0
  (test_widget))
```

### Showcase

- This is the screenshot for the above code
image

## Additional Notes

- The results are not completely accurate (because of floating point). The user can still use `round()` if they wish.

## Checklist

Please make sure you can check all the boxes that apply to this PR.

- [x] All widgets I've added are correctly documented.
- [x] I added my changes to CHANGELOG.md, if appropriate.
- [x] The documentation in the `docs/content/main` directory has been adjusted to reflect my changes.
- [x] I used `cargo fmt` to automatically format all code before committing

### CODE REVIEW

**Comment by D3vil0p3r** [comment]
Hey @elkowar could you please merge this PR? It is very useful.

**Comment by elkowar** [comment]
Any reason to not just have sin, cos etc and then have a deg2rad and rad2deg function instead? Having degrees and radian versions of all functions seems a bit ehhhhh

**Comment by end-4** [comment]
alright
that makes sense, i'm on it

**Comment by end-4** [comment]
Done
I also tested locally and it worked

**Comment by end-4** [comment]
Seems to be a problem with dependencies, so I updated deps
Can I get another check please?

**Comment by D3vil0p3r** [comment]
@end-4 thank you. @elkowar what do you think about it?

**Comment by xBiei** [comment]
Hi, Any updates on this PR? @elkowar

**Comment by elkowar** [comment]
Looks great! If you fix the broken Cargo.lock, I'll be happy to merge this! Sorry for being so slow to respond ^^'

**Comment by end-4** [comment]
hopefully that fixes it

**Comment by elkowar** [comment]
Thanks for your work!

**Pull request merged**
